# Local development setup building MicroPowerManager containers in development mode
services:
  backend-dev:
    container_name: backend-dev
    build:
      dockerfile: docker/DockerfileBackendDev
    env_file: ./dev/.env.micropowermanager-backend
    depends_on:
      redis:
        condition: service_started
    links:
      - redis:redis
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./src/backend:/var/www/html
      - backend_php_vendor:/var/www/html/vendor
      - storage_data:/var/www/html/storage
    healthcheck:
      test: [CMD, curl, -f, http://localhost/up]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 100

  frontend-dev:
    container_name: frontend-dev
    build:
      dockerfile: docker/DockerfileFrontendDev
    env_file: ./dev/.env.micropowermanager-frontend
    ports:
      - 8001:8080
    volumes:
      - ./src/frontend:/app/
      - frontend_node_modules:/app/node_modules/

  scheduler-dev:
    container_name: scheduler-dev
    build:
      dockerfile: docker/DockerfileSchedulerDev
    env_file: ./dev/.env.micropowermanager-backend
    depends_on:
      redis:
        condition: service_started
    links:
      - redis:redis
    volumes:
      - ./src/backend:/var/www/html
      - scheduler_php_vendor:/var/www/html/vendor
      - storage_data:/var/www/html/storage

  queue-worker-dev:
    container_name: queue-worker-dev
    build:
      dockerfile: docker/DockerfileQueueWorkerDev
    env_file: ./dev/.env.micropowermanager-backend
    depends_on:
      redis:
        condition: service_started
    links:
      - redis:redis
    volumes:
      - ./src/backend:/var/www/html
      - queue_worker_php_vendor:/var/www/html/vendor
      - storage_data:/var/www/html/storage

  redis:
    container_name: redis
    image: redis:5
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  redis_data:
  frontend_node_modules:
  backend_php_vendor:
  scheduler_php_vendor:
  queue_worker_php_vendor:
  storage_data:
