# Local setup building MicroPowerManager containers in production mode
services:
  backend-prod:
    container_name: backend-prod
    build:
      context: .
      dockerfile: docker/DockerfileBackendProd
    env_file: ./dev/.env.micropowermanager-backend-mympm
    depends_on:
      redis:
        condition: service_started
    links:
      - redis:redis
    ports:
      - 8000:80
      - 8443:443
    healthcheck:
      test: [CMD, curl, -f, http://localhost/up]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 100

  frontend-prod:
    container_name: frontend-prod
    build:
      context: .
      dockerfile: docker/DockerfileFrontendProd
    env_file: ./dev/.env.micropowermanager-frontend-mympm
    ports:
      - 8001:80

  scheduler-prod:
    container_name: scheduler-prod
    build:
      context: .
      dockerfile: docker/DockerfileSchedulerProd
    # micropowermanager-scheduler is a backend service and uses the same configuration as micropowermanager-backend
    env_file: ./dev/.env.micropowermanager-backend-mympm
    depends_on:
      redis:
        condition: service_started
    links:
      - redis:redis

  queue-worker-prod:
    container_name: queue-worker-prod
    build:
      context: .
      dockerfile: docker/DockerfileQueueWorkerProd
    # micropowermanager-queue-worker is a backend service and uses the same configuration as micropowermanager-backend
    env_file: ./dev/.env.micropowermanager-backend-mympm
    depends_on:
      redis:
        condition: service_started
    links:
      - redis:redis

  redis:
    container_name: redis
    image: redis:5
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  mysql_data:
  redis_data:
